ALTER TABLE uploads ADD COLUMN expires_at TEXT NOT NULL DEFAULT '';
ALTER TABLE uploads ADD COLUMN error TEXT NOT NULL DEFAULT '';
ALTER TABLE uploads ADD COLUMN mime TEXT NOT NULL DEFAULT '';
ALTER TABLE uploads ADD COLUMN media_file_id TEXT NOT NULL DEFAULT '';
ALTER TABLE uploads ADD COLUMN item_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE uploads ADD COLUMN item_id TEXT NOT NULL DEFAULT '';

UPDATE libraries SET uploads_enabled = 1;
