ALTER TABLE users ADD COLUMN is_temporary INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN expires_at TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN max_sessions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN party_only INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS users_temporary_expiry ON users(is_temporary, expires_at);
